# config.yaml
prompts:
  grading: |
    Please grade the following student submission according to this rubric:
    
    Submission:
    {submission}
    
    Rubric:
    {rubric}
    
    Provide a detailed evaluation and final score.

paths:
  submissions: data/submissions  # Adjust if your paths are different
  rubrics: data/rubrics
  results: data/results

rubric_designer:
  iterations: 3  # Number of iterations for rubric improvement
  sample_size: 10  # Number of submissions to sample per iteration